# Generated by Django 5.1.7 on 2025-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('tas', 'Tas'), ('bola', 'Bola'), ('sepatu', 'Sepatu'), ('baju', 'Baju'), ('general', 'General')], default='general', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
            ],
        ),
    ]
